-- Create tables
CREATE TABLE SAILORS (
    SID INT PRIMARY KEY,
    SNAME VARCHAR(255),
    RATING INT,
    AGE INT
);

CREATE TABLE BOATS (
    BID INT PRIMARY KEY,
    BNAME VARCHAR(255),
    COLOR VARCHAR(255)
);

CREATE TABLE RESERVES (
    SID INT,
    BID INT,
    DAY DATE,
    PRIMARY KEY (SID, BID),
    FOREIGN KEY (SID) REFERENCES SAILORS(SID),
    FOREIGN KEY (BID) REFERENCES BOATS(BID)
);

-- Insert sample data
INSERT INTO SAILORS VALUES (1, 'Alice', 5, 25);
INSERT INTO SAILORS VALUES (2, 'Bob', 4, 28);
INSERT INTO SAILORS VALUES (3, 'Charlie', 3, 22);

INSERT INTO BOATS VALUES (101, 'BoatA', 'Red');
INSERT INTO BOATS VALUES (102, 'BoatB', 'Green');
INSERT INTO BOATS VALUES (103, 'BoatC', 'Red');

INSERT INTO RESERVES VALUES (1, 101, '2024-01-01');
INSERT INTO RESERVES VALUES (2, 102, '2024-02-15');
INSERT INTO RESERVES VALUES (3, 103, '2024-03-10');
INSERT INTO RESERVES VALUES (1, 103, '2024-04-20');

-- Queries
-- i. Find the names of sailors who have reserved a red boat
SELECT SNAME
FROM SAILORS
WHERE SID IN (SELECT SID FROM RESERVES WHERE BID IN (SELECT BID FROM BOATS WHERE COLOR = 'Red'));

-- ii. Find the names of sailors who have reserved a red or a green boat
SELECT SNAME
FROM SAILORS
WHERE SID IN (SELECT SID FROM RESERVES WHERE BID IN (SELECT BID FROM BOATS WHERE COLOR IN ('Red', 'Green')));

-- iii. Find the names of sailors who have reserved all boats called "Interlake".
SELECT SNAME
FROM SAILORS
WHERE NOT EXISTS (
    SELECT BID
    FROM BOATS
    WHERE BNAME = 'Interlake'
    EXCEPT
    SELECT BID
    FROM RESERVES
    WHERE SID = SAILORS.SID
);